var str = '';

str += '<aside class="aside">';
str += '  <ul class="asideNav">';
str += '    <li>';
str += '      <a href="#">';
str += '        <b>예상연금조회</b>';
str += '        <i class="icon icon1"></i>';
str += '      </a>';
str += '    </li>';
str += '    <li>';
str += '      <a href="#">';
str += '        <b>상담신청</b>';
str += '        <i class="icon icon2"></i>';
str += '      </a>';
str += '    </li>';
str += '    <li>';
str += '      <a href="#">';
str += '        <b>연계신청</b>';
str += '        <i class="icon icon3"></i>';
str += '      </a>';
str += '    </li>';
str += '    <li>';
str += '      <a href="#">';
str += '        <b>연계급여청구</b>';
str += '        <i class="icon icon4"></i>';
str += '      </a>';
str += '    </li>';
str += '    <li>';
str += '      <a href="#">';
str += '        <b>지사찾기</b>';
str += '        <i class="icon icon5"></i>';
str += '      </a>';
str += '    </li>';
str += '  </ul>';
str += '</aside>';
str += '<footer class="mFooterCon">';
str += '  <div class="ftLinks">';
str += '    <div class="area">';
str += '      <a href="#">';
str += '        <i class="icon icon1"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">120</b>';
str += '          <span>보건복지부</span>';
str += '        </div>';
str += '      </a>';
str += '      <a href="#">';
str += '        <i class="icon icon2"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">1355</b>';
str += '          <span>국민연금</span>';
str += '        </div>';
str += '      </a>';
str += '      <a href="#">';
str += '        <i class="icon icon3"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">1588-4321</b>';
str += '          <span>공무원연금</span>';
str += '        </div>';
str += '      </a>';
str += '      <a href="#">';
str += '        <i class="icon icon4"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">1588-4110</b>';
str += '          <span>사학연금</span>';
str += '        </div>';
str += '      </a>';
str += '      <a href="#">';
str += '        <i class="icon icon5"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">02-3146-6471</b>';
str += '          <span>군인연금</span>';
str += '        </div>';
str += '      </a>';
str += '      <a href="#">';
str += '        <i class="icon icon6"></i>';
str += '        <div>';
str += '          <b class="fontMontserrat">02-3278-7700</b>';
str += '          <span>별정우체국연금</span>';
str += '        </div>';
str += '      </a>';
str += '    </div>';
str += '  </div>';
str += '  <div class="area mfBody">';
str += '    <div class="fLinks">';
str += '      <a href="https://www.nps.or.kr/jsppage/members/personal_policy_com.jsp" class="colorBlue" target="_blank">개인정보처리방침 <img src="../../images/common/ico_link_blue.svg" alt="새창 이동"></a>';
str += '      <a href="#">홈페이지이용안내</a>';
str += '      <a href="../home/HO_00_06_01.html">서비스약관</a>';
str += '      <a href="../home/HO_00_06_02.html">지사찾기</a>';
str += '    </div>';
str += '    <div class="fSNS">';
str += '      <div class="t">';
str += '        <select title="관련사이트 선택" class="linkUrl">';
str += '          <option value="">관련사이트 바로가기</option>';
str += '          <option value="http://www.mohw.go.kr ">보건복지부</option>';
str += '          <option value="http://www.nps.or.kr">국민연금공단</option>';
str += '          <option value="http://www.geps.or.kr">공무원연금공단</option>';
str += '          <option value="http://www.ktpf.or.kr">사립학교교직원연금공단</option>';
str += '          <option value="https://www.mps.mil.kr">국방부 군인연금</option>';
str += '          <option value="http://www.popa.or.kr">별정우체국연금관리단</option>';
str += '          <option value="http://csa.nps.or.kr">국민연금 노후준비서비스</option>';
str += '          <option value="http://100lifeplan.fss.or.kr">금융감독원 통합연금포탈</option>';
str += '        </select>';
str += '        <button type="button" class="fSNSBtn">이동</button>';
str += '      </div>';
str += '      <div class="b">';
str += '        <a href="#" class="kakao" target="_blank"><i>카카오톡</i></a>';
str += '        <a href="#" class="facebook" target="_blank"><i>페이스북</i></a>';
str += '        <a href="#" class="twitter" target="_blank"><i>트위터</i></a>';
str += '        <a href="#" class="instagram" target="_blank"><i>인스타그램</i></a>';
str += '        <a href="#" class="wa" target="_blank"><i>WEB 접근성 인증마크</i></a>';
str += '      </div>';
str += '    </div>';
str += '    <div class="address">';
str += '      <p>';
str += '        <span>[제도정책] 세종특별자치시 도움4로 13 보건복지부 (정부세종청사 10동)</span>';
str += '        <span>[시스템 운영] 전북 전주시 덕진구 기자로 180(만성동) 국민연금</span>';
str += '      </p>';
str += '      <p>Copyright (C) by ppsl All right reserved.</p>';
str += '    </div>';
str += '  </div>';
str += '</footer>';


document.write(str);
