var str = '';

str += '<nav class="skipnav">';
str += '  <a href="#contentLink">본문 바로가기</a>';
str += '  <a href="#menuLink">메뉴 바로가기</a>';
str += '</nav>';
str += '';
str += '<header class="header">';
str += '  <div class="global">';
str += '    <div class="area">';
str += '      <div>';
str += '        <span class="colorBlue">홍길동님 안녕하세요.</span> <button type="button" class="logOutBtn">로그아웃</button>';
str += '      </div>';
str += '      <div class="loginSpace">';
str += '        <span>로그인 유지</span> <span class="time">29:59</span> <button type="button" class="timeExtensionBtn">시간연장</button>';
str += '      </div>';
str += '      <div class="textSpace">';
str += '        <span>화면크기</span>';
str += '        <button type="button" class="fontSize increaseBtn"><i>확대</i></button>';
str += '        <button type="button" class="fontSize decreaseBtn"><i>축소</i></button>';
str += '      </div>';
str += '    </div>';
str += '  </div>';
str += '  <div class="menu">';
str += '    <div class="area">';
str += '      <h1><a href="#"><img src="../../images/common/ci.svg" alt="공적연금연계제도"></a></h1>';
str += '      <nav id="menuLink" class="gnb">';
str += '        <ul class="depth1">';
str += '          <li><a href="../guide/HO_01_01_01_01.html" data-menu="depth_1">안내</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../guide/HO_01_01_01_01.html" data-menu="depth_1_1">제도소개</a>';
str += '                <ul class="depth3">';
str += '                  <li><a href="../guide/HO_01_01_01_01.html" data-menu="depth_1_1_1">연금연계제도</a></li>';
str += '                  <li><a href="../guide/HO_01_01_02_01.html" data-menu="depth_1_1_2">용어집</a></li>';
str += '                  <li><a href="../guide/HO_01_01_03.html" data-menu="depth_1_1_3">관계기관법령</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="../guide/HO_01_02_01.html" data-menu="depth_1_2">신청/청구안내</a>';
str += '                <ul class="depth3">';
str += '                  <li><a href="../guide/HO_01_02_01.html" data-menu="depth_1_2_1">연계신청</a></li>';
str += '                  <li><a href="../guide/HO_01_02_02.html" data-menu="depth_1_2_2">반납금납부</a></li>';
str += '                  <li><a href="../guide/HO_01_02_03_01.html" data-menu="depth_1_2_3">연금종류 및 청구</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="../guide/HO_01_03_01.html" data-menu="depth_1_3">신고/절차안내</a>';
str += '                <ul class="depth3">';
str += '                  <li><a href="../guide/HO_01_03_01.html" data-menu="depth_1_3_1">사망신고안내</a></li>';
str += '                  <li><a href="../guide/HO_01_03_02.html" data-menu="depth_1_3_2">권리구제절차</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="../guide/HO_01_04_01.html" data-menu="depth_1_4">상담사례</a></li>';
str += '              <li><a href="../guide/HO_01_05_01.html" data-menu="depth_1_5">찾아오시는길</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="../consultation/HO_02_01_01.html" data-menu="depth_2">상담</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../consultation/HO_02_01_01.html" data-menu="depth_2_1">상담</a></li>';
str += '              <li><a href="../consultation/HO_02_02_01.html" data-menu="depth_2_2">상담FAQ</a></li>';
str += '              <li><a href="../consultation/HO_02_03_01.html" data-menu="depth_2_3">전산문의</a></li>';
str += '              <li><a href="../consultation/HO_02_04_01.html" data-menu="depth_2_4">제도개선</a></li>';
str += '              <li><a href="../consultation/HO_02_05_01.html" data-menu="depth_2_5">심사요청</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="../apply/HO_02_06_01.html" data-menu="depth_3">신청</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../apply/HO_02_06_01.html" data-menu="depth_3_1">반납금 모의계산</a>';
str += '              <li><a href="../apply/HO_03_01_01.html" data-menu="depth_3_2">연계신청</a></li>';
str += '              <li><a href="../apply/HO_03_05_01.html" data-menu="depth_3_3">신청정보변경</a></li>';
str += '              <li><a href="../apply/HO_03_06_01.html" data-menu="depth_3_4">신청상태조회</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="../charge/HO_04_01_01.html" data-menu="depth_4">청구</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../charge/HO_04_01_01.html" data-menu="depth_4_1">연계연금청구</a></li>';
str += '              <li><a href="../charge/HO_04_02_01.html" data-menu="depth_4_2">수급계좌변경</a></li>';
str += '              <li><a href="../charge/HO_04_03_01.html" data-menu="depth_4_3">상태조회</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="../inform/HO_05_01_01.html" data-menu="depth_5">알림</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../inform/HO_05_01_01.html" data-menu="depth_5_1">공지사항</a></li>';
str += '              <li><a href="../inform/HO_05_02_01.html" data-menu="depth_5_2">자료실</a></li>';
str += '              <li><a href="../inform/HO_05_03_01.html" data-menu="depth_5_3">연금연계소식</a></li>';
str += '              <li><a href="../inform/HO_05_04_01.html" data-menu="depth_5_4">이용안내</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="../mypage/HO_06_01_01.html" data-menu="depth_6">마이페이지</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="../mypage/HO_06_01_01.html" data-menu="depth_6_1">나의현황</a>';
str += '                <ul class="depth3">';
str += '                  <li><a href="../mypage/HO_06_01_01.html" data-menu="depth_6_1_1">신청청구현황</a></li>';
str += '                  <li><a href="../mypage/HO_06_01_02.html" data-menu="depth_6_1_2">연금수령현황</a></li>';
str += '                  <li><a href="../mypage/HO_06_01_03.html" data-menu="depth_6_1_3">반납금현황</a></li>';
str += '                  <li><a href="../mypage/HO_06_01_04.html" data-menu="depth_6_1_4">상담내역</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="../mypage/HO_06_02_01.html" data-menu="depth_6_2">예상연금/반납금</a>';
str += '                <ul class="depth3">';
str += '                  <li><a href="../mypage/HO_06_02_01.html" data-menu="depth_6_2_1">예상연금조회</a></li>';
str += '                  <li><a href="../mypage/HO_06_02_05.html" data-menu="depth_6_2_2">예상반납금조회</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="../mypage/HO_06_03_01.html" data-menu="depth_6_3">증명서발급요청</a></li>';
str += '              <li><a href="../mypage/HO_06_04_01.html" data-menu="depth_6_4">증명서</a></li>';
str += '            </ul>';
str += '          </li>';
str += '        </ul>';
str += '      </nav>';
str += '      <div class="btnsWrap">';
str += '        <button type="button" class="allSearchBtn"><i>통합검색</i></button>';
str += '        <button type="button" class="allMenuBtn" aria-controls="allMenu_pop"><i>전체 메뉴</i></button>';
str += '      </div>';
str += '    </div>';
str += '    <div class="subMenuBlind"></div>';
str += '  </div>';
str += '</header>';


document.write(str);


