var str = '';

str += '<nav class="skipnav">';
str += '  <a href="#contentLink">본문 바로가기</a>';
str += '  <a href="#menuLink">메뉴 바로가기</a>';
str += '</nav>';
str += '<!-- PC 메뉴 -->';
str += '<header class="onlyPC header">';
str += '  <div class="global">';
str += '    <div class="area">';
str += '      <div>';
str += '        <span class="colorBlue">홍길동님 안녕하세요.</span> <button type="button" class="logOutBtn">로그아웃</button>';
str += '      </div>';
str += '      <div class="loginSpace">';
str += '        <span>로그인 유지</span> <span class="time">29:59</span> <button type="button" class="timeExtensionBtn">시간연장</button>';
str += '      </div>';
str += '      <div class="textSpace">';
str += '        <span>화면크기</span>';
str += '        <button type="button" class="fontSize increaseBtn">+</button>';
str += '        <button type="button" class="fontSize decreaseBtn">-</button>';
str += '      </div>';
str += '      <div class="searchSpace">';
str += '        <span class="searchBox"><input type="text" title="검색어 입력" placeholder="검색어를 입력하세요."><button type="button" class="searchBtn"><i>검색</i></button></span>';
str += '      </div>';
str += '    </div>';
str += '  </div>';
str += '  <div class="menu">';
str += '    <div class="area">';
str += '      <h1><a href="#"><img src="../../images/common/ci.svg" alt="공적연금연계제도"></a></h1>';
str += '      <nav id="menuLink" class="gnb">';
str += '        <ul class="depth1">';
str += '          <li><a href="#">안내</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">제도소개</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">신청/청구안내</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">신고/절차안내</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">상담사례</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">찾아오시는길</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="#">상담</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">상담</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">상담FAQ</a></li>';
str += '              <li><a href="#">전산문의</a></li>';
str += '              <li><a href="#">제도개선</a></li>';
str += '              <li><a href="#">심사요청</a></li>';
str += '              <li><a href="#">반납금 모의계산</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="#">신청</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">연계신청</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">신청정보변경</a></li>';
str += '              <li><a href="#">신청상태조회</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="#">청구</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">연계연금청구</a>';
str += '                <ul class="depth2">';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                  <li><a href="#">33333</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">수급계좌변경</a></li>';
str += '              <li><a href="#">상태조회</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="#">알림</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">공지사항</a></li>';
str += '              <li><a href="#">자료실</a></li>';
str += '              <li><a href="#">연금연계소식</a></li>';
str += '              <li><a href="#">이용안내</a></li>';
str += '            </ul>';
str += '          </li>';
str += '          <li><a href="#">마이페이지</a>';
str += '            <ul class="depth2">';
str += '              <li><a href="#">나의현황</a>';
str += '                <ul>';
str += '                  <li><a href="#">신청청구현황</a></li>';
str += '                  <li><a href="#">연금수령현황</a></li>';
str += '                  <li><a href="#">반납금현황</a></li>';
str += '                </ul>';
str += '              </li>';
str += '              <li><a href="#">예상연금</a></li>';
str += '              <li><a href="#">예상반납금</a></li>';
str += '              <li><a href="#">증명서 발급요청</a></li>';
str += '              <li><a href="#">증명서</a></li>';
str += '            </ul>';
str += '          </li>';
str += '        </ul>';
str += '      </nav>';
str += '      <button type="button" class="allMenuBtn" aria-controls="allMenu_pop"><i>전체 메뉴</i></button>';
str += '    </div>';
str += '    <div class="subMenuBlind"></div>';
str += '  </div>';
str += '</header>';
str += '<!-- //PC 메뉴 -->';
str += '<!-- Mobile 메뉴 -->';
str += '<header class="onlyMobile moHeader">';
str += '  <div class="global">';
str += '    <h1><a href="#"><img src="../../images/common/ci.svg" alt="공적연금연계제도"></a></h1>';
str += '    <div>';
str += '      <button type="button" class="searchBtn"><i>검색</i></button>';
str += '      <button type="button" class="allMenuBtn" aria-controls="allMenu_pop"><i>전체 메뉴</i></button>';
str += '    </div>';
str += '  </div>';
str += '</header>';
str += '<!-- //Mobile 메뉴 -->';


document.write(str);


